# Site settings
title: DW’s Blog
SEOTitle: 大威的博客|DW's Blog
header-img: img/common/home-bg.jpg
email: firmiana628@gmail.com
description: "我不写代码,我只是代码的搬运工。"
keyword: "扯淡呢"
url: "http://firmiana628.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: true
weibo_username:   #  2692413341
zhihu_username:   #  mu-rong-er-gou-39
github_username:  #  firmiana628
#twitter_username:  
#facebook_username:  



# Build settings
gems: [jekyll-paginate]
#highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Duoshuo settings
#duoshuo_username: daiweilai # Share component is depend on Comment so we can NOT use share only.
#duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: 5c2c47b6a361d270fd09888b94ad77ce
# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "coding....."
sidebar-avatar: http://firmiana628.github.io/img/common/avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0             # A tag will be featured if the size of it is more than this condition value



# Friends
#friends: [
#    {
#        title: "",
#        href: ""
#    },{
#        title: "",
#        href: ""
#    }
#]
